"""
Template management system for AI News System.

This module provides template rendering capabilities with style integration,
supporting multiple content types and consistent presentation.
"""

from typing import Dict, List, Any, Optional, Union
from dataclasses import dataclass
import logging
import re
from datetime import datetime
import json

logger = logging.getLogger(__name__)


@dataclass
class TemplateContext:
    """Context data for template rendering."""
    title: str = ""
    content: str = ""
    author: str = "AI News System"
    date: str = ""
    keywords: List[str] = None
    metadata: Dict[str, Any] = None
    style_class: str = ""

    def __post_init__(self):
        if self.keywords is None:
            self.keywords = []
        if self.metadata is None:
            self.metadata = {}
        if not self.date:
            self.date = datetime.now().strftime("%Y-%m-%d")


class TemplateManager:
    """Manages templates and rendering for AI News System."""

    # Internal template definitions
    _TEMPLATES = {
        "daily_report": """
<article class="daily-report card fade-in">
    <header class="report-header">
        <div class="report-meta">
            <time class="text-sm text-neutral-600">{{date}}</time>
            <span class="ai-badge">AI Generated</span>
        </div>
        <h1 class="text-3xl font-bold text-gradient mt-2 mb-4">{{title}}</h1>
    </header>

    <div class="report-content prose prose-lg max-w-none">
        {{{content}}}
    </div>

    {{#if keywords}}
    <footer class="report-footer mt-8 pt-6 border-t border-neutral-200">
        <h3 class="text-sm font-semibold text-neutral-600 mb-2">Keywords</h3>
        <div class="flex flex-wrap gap-2">
            {{#each keywords}}
            <span class="px-3 py-1 bg-primary-100 text-primary-700 rounded-full text-xs font-medium">{{this}}</span>
            {{/each}}
        </div>
    </footer>
    {{/if}}
</article>
""",
        "research_report": """
<div class="research-report container">
    <header class="report-header section">
        <div class="max-w-4xl mx-auto">
            <div class="report-meta flex items-center gap-4 mb-4">
                <time class="text-sm text-neutral-600">{{date}}</time>
                <span class="ai-badge">Research Report</span>
            </div>
            <h1 class="text-4xl font-bold text-gradient mb-6">{{title}}</h1>
            {{#if metadata.subtitle}}
            <p class="text-xl text-neutral-600 mb-8">{{metadata.subtitle}}</p>
            {{/if}}
        </div>
    </header>

    <main class="report-content section">
        <div class="max-w-4xl mx-auto">
            {{{content}}}
        </div>
    </main>

    {{#if keywords}}
    <section class="report-keywords section bg-neutral-50">
        <div class="max-w-4xl mx-auto">
            <h2 class="text-2xl font-bold mb-4">Keywords</h2>
            <div class="grid grid-cols-2 md:grid-cols-3 gap-3">
                {{#each keywords}}
                <div class="flex items-center gap-2 p-3 bg-white rounded-lg shadow-sm">
                    <div class="w-2 h-2 bg-primary-500 rounded-full"></div>
                    <span class="text-sm font-medium">{{this}}</span>
                </div>
                {{/each}}
            </div>
        </div>
    </section>
    {{/if}}

    {{#if metadata.appendix}}
    <section class="report-appendix section">
        <div class="max-w-4xl mx-auto">
            <h2 class="text-2xl font-bold mb-4">Appendix</h2>
            {{{metadata.appendix}}}
        </div>
    </section>
    {{/if}}

    <footer class="report-footer section bg-neutral-900 text-white">
        <div class="max-w-4xl mx-auto text-center">
            <p class="text-sm text-neutral-400">Generated by AI News System</p>
            <p class="text-xs text-neutral-500 mt-2">{{date}}</p>
        </div>
    </footer>
</div>
""",
        "thinking_model": """
<div class="thinking-model glass-card">
    <div class="thinking-header mb-6">
        <div class="flex items-center gap-3 mb-4">
            <div class="w-3 h-3 bg-primary-500 rounded-full ai-glow"></div>
            <span class="text-sm font-semibold text-primary-600">AI THINKING PROCESS</span>
        </div>
        <h1 class="text-2xl font-bold text-gradient">{{title}}</h1>
        <p class="text-neutral-600 mt-2">Analysis and reasoning behind the insights</p>
    </div>

    <div class="thinking-content space-y-4">
        {{{content}}}
    </div>

    <div class="thinking-metadata mt-8 p-4 bg-primary-50 rounded-lg">
        <h3 class="text-sm font-semibold text-primary-700 mb-2">Model Information</h3>
        <dl class="grid grid-cols-2 gap-2 text-sm">
            <dt class="text-neutral-600">Generated:</dt>
            <dd class="text-neutral-900">{{date}}</dd>
            <dt class="text-neutral-600">Model:</dt>
            <dd class="text-neutral-900">{{#if metadata.model}}{{metadata.model}}{{else}}AI Reasoning Engine{{/if}}</dd>
            <dt class="text-neutral-600">Confidence:</dt>
            <dd class="text-neutral-900">{{#if metadata.confidence}}{{metadata.confidence}}{{else}}High{{/if}}</dd>
        </dl>
    </div>
</div>
""",
        "homepage": """
<div class="homepage">
    <!-- Hero Section -->
    <section class="hero-section relative overflow-hidden">
        <div class="absolute inset-0 bg-gradient-ai opacity-10"></div>
        <div class="container relative z-10 py-20 text-center">
            <div class="max-w-4xl mx-auto">
                <h1 class="text-5xl md:text-6xl font-extrabold text-gradient mb-6 slide-in">
                    {{title}}
                </h1>
                {{#if metadata.subtitle}}
                <p class="text-xl md:text-2xl text-neutral-600 mb-8 fade-in">
                    {{{metadata.subtitle}}}
                </p>
                {{/if}}
                <div class="flex flex-col sm:flex-row gap-4 justify-center items-center fade-in">
                    <a href="#latest" class="btn btn-primary px-8 py-3">
                        View Latest News
                    </a>
                    <a href="#research" class="btn btn-secondary px-8 py-3">
                        Browse Research
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- Featured Content -->
    {{#if metadata.featured_items}}
    <section id="latest" class="section featured-section">
        <div class="container">
            <div class="text-center mb-12">
                <h2 class="text-3xl font-bold text-gradient mb-4">Featured Content</h2>
                <p class="text-lg text-neutral-600">Latest AI news and research insights</p>
            </div>
            <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
                {{#each metadata.featured_items}}
                <article class="card fade-in">
                    {{#if this.image}}
                    <div class="article-image h-48 bg-gradient-secondary rounded-t-xl"></div>
                    {{/if}}
                    <div class="p-6">
                        <div class="flex items-center gap-2 mb-3">
                            <span class="text-xs text-primary-600 font-semibold">{{this.category}}</span>
                            <span class="text-xs text-neutral-400">{{this.date}}</span>
                        </div>
                        <h3 class="text-xl font-bold mb-2">{{this.title}}</h3>
                        <p class="text-neutral-600 mb-4">{{{this.excerpt}}}</p>
                        <a href="{{this.url}}" class="text-primary-600 font-semibold hover:text-primary-700">Read more →</a>
                    </div>
                </article>
                {{/each}}
            </div>
        </div>
    </section>
    {{/if}}

    <!-- Categories -->
    <section class="section categories-section bg-neutral-50">
        <div class="container">
            <div class="text-center mb-12">
                <h2 class="text-3xl font-bold text-gradient mb-4">Categories</h2>
                <p class="text-lg text-neutral-600">Explore AI news by category</p>
            </div>
            <div class="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto">
                {{#each metadata.categories}}
                <div class="category-card card text-center">
                    <div class="w-12 h-12 bg-gradient-primary rounded-full mx-auto mb-4"></div>
                    <h3 class="text-lg font-bold mb-2">{{this.name}}</h3>
                    <p class="text-neutral-600 text-sm mb-4">{{this.description}}</p>
                    <a href="{{this.url}}" class="text-primary-600 font-semibold text-sm">Explore →</a>
                </div>
                {{/each}}
            </div>
        </div>
    </section>

    <!-- Newsletter -->
    <section class="section newsletter-section bg-gradient-primary text-white">
        <div class="container">
            <div class="max-w-3xl mx-auto text-center">
                <h2 class="text-3xl font-bold mb-4">Stay Updated</h2>
                <p class="text-lg mb-8 opacity-90">Get the latest AI news delivered to your inbox</p>
                <div class="flex flex-col sm:flex-row gap-4 justify-center max-w-md mx-auto">
                    <input type="email" placeholder="Enter your email" class="flex-1 px-4 py-3 rounded-md text-neutral-900">
                    <button class="btn btn-secondary px-6 py-3">Subscribe</button>
                </div>
            </div>
        </div>
    </section>
</div>
""",
        "article_summary": """
<div class="article-summary card">
    <header class="summary-header mb-4">
        <h3 class="text-lg font-bold text-neutral-800 mb-2">{{title}}</h3>
        <div class="flex items-center gap-2 text-sm text-neutral-600">
            <time>{{date}}</time>
            {{#if metadata.read_time}}
            <span>•</span>
            <span>{{metadata.read_time}} min read</span>
            {{/if}}
        </div>
    </header>

    <div class="summary-content">
        <p class="text-neutral-600 leading-relaxed">{{content}}</p>
    </div>

    {{#if keywords}}
    <div class="summary-keywords mt-4">
        <div class="flex flex-wrap gap-2">
            {{#each keywords}}
            <span class="px-2 py-1 bg-neutral-100 text-neutral-700 rounded text-xs">{{this}}</span>
            {{/each}}
        </div>
    </div>
    {{/if}}
</div>
""",
        "minimal": """
<div class="minimal-content max-w-4xl mx-auto px-6 py-8">
    <header class="mb-8">
        <h1 class="text-3xl font-bold text-neutral-900 mb-2">{{title}}</h1>
        {{#if metadata.subtitle}}
        <p class="text-lg text-neutral-600">{{metadata.subtitle}}</p>
        {{/if}}
        <div class="text-sm text-neutral-500 mt-4">
            {{date}} {{#if author}}• {{author}}{{/if}}
        </div>
    </header>

    <main class="prose prose-lg max-w-none">
        {{{content}}}
    </main>
</div>
"""
    }

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """Initialize TemplateManager with optional configuration."""
        self.config = config or {}
        self.custom_templates = {}
        logger.info("TemplateManager initialized")

    def get_template(self, template_type: str) -> str:
        """
        Get template content for specified type.

        Args:
            template_type: Type of template (daily_report, research_report, etc.)

        Returns:
            Template content as string

        Raises:
            ValueError: If template type is not found
        """
        logger.info(f"Getting template for type: {template_type}")

        # Check custom templates first
        if template_type in self.custom_templates:
            logger.debug(f"Using custom template for {template_type}")
            return self.custom_templates[template_type]

        # Check built-in templates
        if template_type in self._TEMPLATES:
            logger.debug(f"Using built-in template for {template_type}")
            return self._TEMPLATES[template_type]

        # Try partial matches
        for key, template in self._TEMPLATES.items():
            if template_type in key or key in template_type:
                logger.warning(f"Using approximate match for template: {key} for request: {template_type}")
                return template

        logger.error(f"Template not found: {template_type}")
        raise ValueError(f"Template type '{template_type}' not found")

    def _render_placeholders(self, template: str, data: Dict[str, Any]) -> str:
        """
        Simple template placeholder replacement.

        Args:
            template: Template string with {{placeholders}}
            data: Data to replace placeholders

        Returns:
            Rendered template string
        """
        result = template

        # Handle simple {{variable}} replacements
        for key, value in data.items():
            if isinstance(value, str):
                result = result.replace(f"{{{{{key}}}}}", value)
            elif isinstance(value, (int, float)):
                result = result.replace(f"{{{{{key}}}}}", str(value))

        # Handle conditional blocks {{#if condition}}...{{/if}}
        def handle_if_blocks(text: str) -> str:
            """Handle conditional blocks."""
            if_pattern = r'\{\{#if\s+(\w+)\}\}(.*?)\{\{/if\}\}'

            def replace_if(match):
                condition = match.group(1)
                content = match.group(2)

                # Check if condition exists and is truthy
                if condition in data and data[condition]:
                    # Handle nested placeholders in the content
                    nested_result = content
                    for key, value in data.items():
                        if isinstance(value, str):
                            nested_result = nested_result.replace(f"{{{{{key}}}}}", value)
                        elif isinstance(value, (int, float)):
                            nested_result = nested_result.replace(f"{{{{{key}}}}}", str(value))
                    return nested_result
                else:
                    return ''

            return re.sub(if_pattern, replace_if, text, flags=re.DOTALL)

        result = handle_if_blocks(result)

        # Handle {{#each items}}...{{/each}} loops
        def handle_each_blocks(text: str) -> str:
            """Handle iteration blocks."""
            each_pattern = r'\{\{#each\s+(\w+)\}\}(.*?)\{\{/each\}\}'

            def replace_each(match):
                iterator_name = match.group(1)
                content = match.group(2)

                if iterator_name in data and isinstance(data[iterator_name], list):
                    items = data[iterator_name]
                    results = []

                    for item in items:
                        item_result = content

                        # Determine context for item
                        if isinstance(item, dict):
                            # Use item properties
                            for key, value in item.items():
                                if isinstance(value, str):
                                    item_result = item_result.replace(f"{{{{this.{key}}}}}", value)
                                elif isinstance(value, (int, float)):
                                    item_result = item_result.replace(f"{{{{this.{key}}}}}", str(value))
                        else:
                            # Direct value
                            item_result = item_result.replace("{{this}}", str(item))

                        results.append(item_result)

                    return ''.join(results)
                else:
                    return ''

            return re.sub(each_pattern, replace_each, text, flags=re.DOTALL)

        result = handle_each_blocks(result)

        # Handle nested properties {{metadata.key}}
        def handle_nested_properties(text: str) -> str:
            """Handle nested property access."""
            nested_pattern = r'\{\{(\w+)\.(\w+)\}\}'

            def replace_nested(match):
                obj_name = match.group(1)
                prop_name = match.group(2)

                if obj_name in data and isinstance(data[obj_name], dict):
                    obj = data[obj_name]
                    if prop_name in obj:
                        value = obj[prop_name]
                        return str(value) if not isinstance(value, str) else value

                return match.group(0)  # Return original if not found

            return re.sub(nested_pattern, replace_nested, text)

        result = handle_nested_properties(result)

        return result

    def render_with_style(self, template_type: str, data: Dict[str, Any],
                         style_context: Optional[Dict[str, Any]] = None) -> str:
        """
        Render template with style integration.

        Args:
            template_type: Type of template to render
            data: Data to fill template placeholders
            style_context: Additional style/behavioral context

        Returns:
            Complete rendered HTML with styles
        """
        logger.info(f"Rendering template with style: {template_type}")

        template = self.get_template(template_type)
        rendered = self._render_placeholders(template, data)

        # Add style wrappers if specified
        if style_context:
            wrapper_class = style_context.get('wrapper_class', '')
            if wrapper_class:
                rendered = f'<div class="{wrapper_class}">{rendered}</div>'

        logger.info("Template rendering completed")
        return rendered

    def add_custom_template(self, name: str, template: str):
        """
        Add a custom template.

        Args:
            name: Template name/identifier
            template: Template content
        """
        logger.info(f"Adding custom template: {name}")
        self.custom_templates[name] = template

    def get_available_templates(self) -> List[str]:
        """Get list of available template types."""
        built_in = list(self._TEMPLATES.keys())
        custom = list(self.custom_templates.keys())
        return sorted(built_in + custom)

    def validate_template(self, template_type: str, required_fields: List[str]) -> bool:
        """
        Validate that a template contains all required fields.

        Args:
            template_type: Type of template to validate
            required_fields: List of required field names

        Returns:
            True if all fields are present
        """
        logger.info(f"Validating template: {template_type}")

        try:
            template = self.get_template(template_type)

            missing_fields = []
            for field in required_fields:
                placeholder = f"{{{{{field}}}}}"
                if placeholder not in template:
                    # Check for nested fields (e.g., metadata.field)
                    nested_pattern = f"{{{{metadata.{field}}}}}"
                    if nested_pattern not in template:
                        missing_fields.append(field)

            if missing_fields:
                logger.warning(f"Template {template_type} missing fields: {missing_fields}")
                return False

            logger.info(f"Template {template_type} validation passed")
            return True

        except Exception as e:
            logger.error(f"Template validation failed: {e}")
            return False

    def render_daily_report(self, title: str, content: str, keywords: Optional[List[str]] = None,
                           metadata: Optional[Dict[str, Any]] = None) -> str:
        """Convenience method for rendering daily reports."""
        context = TemplateContext(
            title=title,
            content=content,
            keywords=keywords or [],
            metadata=metadata or {}
        )
        data = {
            "title": context.title,
            "content": context.content,
            "keywords": context.keywords,
            "date": context.date,
            "metadata": context.metadata
        }
        return self.render_with_style("daily_report", data)

    def render_research_report(self, title: str, content: str,
                              metadata: Optional[Dict[str, Any]] = None) -> str:
        """Convenience method for rendering research reports."""
        context = TemplateContext(
            title=title,
            content=content,
            metadata=metadata or {}
        )
        data = {
            "title": context.title,
            "content": context.content,
            "date": context.date,
            "metadata": context.metadata
        }
        return self.render_with_style("research_report", data)

    def render_thinking_model(self, title: str, content: str,
                             metadata: Optional[Dict[str, Any]] = None) -> str:
        """Convenience method for rendering thinking models."""
        context = TemplateContext(
            title=title,
            content=content,
            metadata=metadata or {}
        )
        data = {
            "title": context.title,
            "content": context.content,
            "date": context.date,
            "metadata": context.metadata
        }
        return self.render_with_style("thinking_model", data)

    def render_homepage(self, title: str, metadata: Optional[Dict[str, Any]] = None) -> str:
        """Convenience method for rendering homepage."""
        context = TemplateContext(
            title=title,
            metadata=metadata or {}
        )
        data = {
            "title": context.title,
            "date": context.date,
            "metadata": context.metadata
        }
        return self.render_with_style("homepage", data)
